development: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: kanban
  username: postgres
  password: postgres
  pool: 10
  # timeout: 86400
  # reconnect: true

test: &test
  <<: *default
  database: kanban_test

cucumber:
  <<: *test

production:
  <<: *default
  database: kanban_production
