# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kanban
  pool: 5

development:
  <<: *base
  username: root
  password:
  socket: /tmp/mysql.sock

qa:
  <<: *base
  username: root
  password:

production:
  <<: *base
  username: root
  password:

test: &test
  <<: *base
  username: root
  password:
  database: ezlaw_test

cucumber:
  <<: *test
